"""File-level cleaning rules.

Har rule ek predicate hai: kya ye file drop honi chahiye? (spec: duplicates,
generated code, vendor folders, binaries, minified JS, lock files, venvs, cache
folders, notebook outputs, huge files, corrupted encodings). Dedup alag module me
hai; ye rules structural/heuristic hain.

Return convention: predicates bool return karte hain. `notebook_stripped` content
transform karta hai.
"""

from __future__ import annotations

import json

# Path segments that mark vendored / build / cache / env dirs.
VENDOR_SEGMENTS = {
    "node_modules", "vendor", "third_party", "thirdparty", "bower_components",
    "dist", "build", "out", "target", ".git", ".svn", ".hg", "venv", ".venv",
    "env", ".env", "__pycache__", "site-packages", ".mypy_cache", ".pytest_cache",
    ".cache", ".tox", ".next", ".nuxt", "coverage", ".gradle", ".idea", ".vscode",
    "Pods", "DerivedData", "bin", "obj",
}

LOCKFILES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock",
    "Pipfile.lock", "Cargo.lock", "go.sum", "Gemfile.lock", "composer.lock",
    "flake.lock", "bun.lockb",
}

GENERATED_MARKERS = (
    "do not edit", "@generated", "autogenerated", "auto-generated",
    "generated by", "this file was automatically generated", "code generated by",
    "@nocheck", "this file is generated",
)


def path_segments(path: str) -> list:
    return [p for p in path.replace("\\", "/").split("/") if p]


def is_vendor_path(path: str) -> bool:
    return any(seg in VENDOR_SEGMENTS for seg in path_segments(path))


def is_lockfile(path: str) -> bool:
    return path_segments(path)[-1] in LOCKFILES if path else False


def is_binary(data: bytes) -> bool:
    """Heuristic: NUL byte present, or a high ratio of non-text bytes."""
    if not data:
        return False
    if b"\x00" in data:
        return True
    text_chars = bytes(range(0x20, 0x7F)) + b"\n\r\t\f\b"
    nontext = sum(b not in text_chars for b in data[:4096])
    return nontext / min(len(data), 4096) > 0.30


def has_corrupted_encoding(data: bytes) -> bool:
    """True if bytes are not valid UTF-8 (treat as corrupted/undecodable)."""
    try:
        data.decode("utf-8")
        return False
    except UnicodeDecodeError:
        return True


def is_minified(path: str, text: str, max_line_length: int = 1000) -> bool:
    """Minified/one-line bundles: `.min.` in name, or very long avg lines."""
    base = path_segments(path)[-1].lower() if path else ""
    if ".min." in base:
        return True
    if not text:
        return False
    lines = text.split("\n")
    longest = max((len(ln) for ln in lines), default=0)
    if longest > max_line_length:
        # long lines + very few newlines => bundled/minified
        newline_ratio = text.count("\n") / max(len(text), 1)
        return newline_ratio < 0.01 or longest > max_line_length * 4
    return False


def is_generated(text: str) -> bool:
    head = (text or "")[:2000].lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def is_too_large(size: int, cap: int) -> bool:
    return size > cap


def is_too_small(size: int, floor: int) -> bool:
    return size < floor


def is_notebook(path: str) -> bool:
    return path.lower().endswith(".ipynb")


def strip_notebook_outputs(text: str) -> str:
    """Remove outputs + execution counts from a Jupyter notebook JSON.

    Content (code cells) rakhta hai; outputs (jinme secrets/huge data ho sakta) hata
    deta hai. Parse fail ho to original wapas (upstream binary/corrupt rule pakdega).
    """
    try:
        nb = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return text
    for cell in nb.get("cells", []):
        if isinstance(cell, dict):
            if "outputs" in cell:
                cell["outputs"] = []
            if "execution_count" in cell:
                cell["execution_count"] = None
    return json.dumps(nb, ensure_ascii=False, indent=1)
