"""Sample repository builder for tests and examples.

Writes a tiny synthetic repo that exercises every RDE filter: good code, tests,
complex code, a duplicate, a generated file, a syntax-broken file, an empty file,
a vendor folder, and a binary blob. Not a demo — a fixture.
"""

from __future__ import annotations

import os

GOOD = '''\
"""A small, well-documented utility module."""


def add(a: int, b: int) -> int:
    """Return the sum of two integers."""
    return a + b


def clamp(x: int, lo: int, hi: int) -> int:
    # keep x within [lo, hi]
    if x < lo:
        return lo
    if x > hi:
        return hi
    return x
'''

TESTS = '''\
from mod import add


def test_add():
    assert add(2, 3) == 5
'''

COMPLEX = '''\
import os
import sys
import json


class Engine:
    def __init__(self, cfg):
        self.cfg = cfg

    def run(self, items):
        out = []
        for it in items:
            if it > 0:
                for j in range(it):
                    if j % 2 == 0:
                        out.append(j)
                    else:
                        try:
                            out.append(1 / j)
                        except ZeroDivisionError:
                            out.append(0)
        return out
'''

GENERATED = '''\
# @generated by protoc. DO NOT EDIT.
class FooProto: pass
'''

BROKEN = "def broken(:\n    return"


def _write(path, content, mode="w"):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, mode) as f:
        f.write(content)


def build_sample(root: str) -> str:
    """Write the sample repo under `root/repoA/` and return `root`."""
    r = os.path.join(root, "repoA")
    _write(os.path.join(r, "mod.py"), GOOD)
    _write(os.path.join(r, "test_mod.py"), TESTS)
    _write(os.path.join(r, "engine.py"), COMPLEX)
    _write(os.path.join(r, "dup.py"), GOOD)                     # duplicate content
    _write(os.path.join(r, "proto_pb2.py"), GENERATED)         # generated -> drop
    _write(os.path.join(r, "broken.py"), BROKEN)               # syntax -> drop
    _write(os.path.join(r, "empty.py"), "   \n")               # empty -> drop
    _write(os.path.join(r, "README.md"), "# repoA\nDemo repository.\n")
    _write(os.path.join(r, "LICENSE"), "MIT License\n\nPermission is hereby...\n")
    _write(os.path.join(r, "config.json"), '{"name": "repoA", "v": 1}\n')
    _write(os.path.join(r, "Dockerfile"), "FROM python:3.11\nRUN pip install x\n")
    _write(os.path.join(r, "node_modules", "junk.py"), "x=1\n")     # vendor -> drop
    _write(os.path.join(r, "blob.bin"), b"\x00\x01\x02\x03BINARY", "wb")  # binary
    return root
