"""Unit tests for the Ryth Data Engine (RDE v1.1).

Pure stdlib — koi torch/numpy nahi. Run:
    cd ryth && python -m pytest tests/test_rde.py -v
    # ya bina pytest:  python tests/test_rde.py
"""

import os
import sys
import tempfile
import shutil

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dataset import (RDEConfig, RDEPipeline, RDSDataset, RDSReader, EmptyDatasetError,
                 ByteTokenizer, verify_lock, tokenizer_hash, SUPPORTED_VERSIONS)
from dataset.cleaner import Cleaner, looks_binary, is_generated
from dataset.language import detect_language
from dataset.validator import Validator
from dataset.quality import _python_signals
from dataset.curriculum import complexity_score, assign_difficulty
from dataset.fim import extract_functions, make_fim, FIM_PREFIX, FIM_MIDDLE
from dataset.record import FileRecord
from tests.sample_data import build_sample
import random

NOW = "2026-07-03T00:00:00+00:00"


# ---------------- cleaner ----------------
def test_looks_binary():
    assert looks_binary(b"\x00\x01\x02BIN")
    assert not looks_binary(b"def f(): return 1\n")


def test_is_generated():
    assert is_generated("# @generated by protoc\nx=1", ("@generated",))
    assert not is_generated("def real(): pass", ("@generated",))


def test_cleaner_dedup_and_utf8():
    cfg = RDEConfig()
    c = Cleaner(cfg)
    r1 = c.clean_bytes("a.py", "r", b"print('hi')\n")
    r2 = c.clean_bytes("b.py", "r", b"print('hi')\n")   # duplicate content
    assert r1 is not None and r2 is None
    assert c.stats["duplicate"] == 1
    assert c.clean_bytes("c.py", "r", b"\xff\xfe not utf8") is None


# ---------------- language ----------------
def test_language_detect():
    assert detect_language("x.py", "print(1)") == "python"
    assert detect_language("Dockerfile", "FROM python:3.11\n") == "dockerfile"
    assert detect_language("x.json", '{"a":1}') == "json"
    assert detect_language("x.json", "not json") == "text"   # invalid json downgraded


# ---------------- validator ----------------
def test_validator_syntax():
    cfg = RDEConfig()
    v = Validator(cfg)
    good = FileRecord(path="g.py", repo="r", text="def f():\n    return 1\n",
                      language="python")
    bad = FileRecord(path="b.py", repo="r", text="def f(:\n  return", language="python")
    assert v.validate(good) is True
    assert v.validate(bad) is False and bad.drop_reason == "syntax"


# ---------------- quality + smart curriculum ----------------
def test_quality_signals():
    code = ("import os\nimport sys\n\n"
            "async def fetch(x: int) -> int:\n"
            "    if x > 0:\n        return x\n    return 0\n")
    s = _python_signals(code)
    assert s["functions"] == 1 and s["async"] >= 1
    assert s["cyclomatic"] >= 2 and s["ast_depth"] > 0
    assert "os" in s["imports"]


def test_smart_curriculum_orders_easy_first():
    simple = FileRecord(path="s.py", repo="r", text="x = 1\n", language="python")
    simple.meta = {"ast_depth": 1, "cyclomatic": 1, "imports": [], "classes": 0,
                   "async": 0, "functions": 0, "n_tokens": 5}
    complex_ = FileRecord(path="c.py", repo="r", text="", language="python")
    complex_.meta = {"ast_depth": 8, "cyclomatic": 12, "imports": ["a", "b", "c"],
                     "classes": 3, "async": 2, "functions": 6, "n_tokens": 2000}
    assert complexity_score(complex_) > complexity_score(simple)
    assert assign_difficulty(simple) == "easy"
    assert assign_difficulty(complex_) == "hard"


# ---------------- FIM ----------------
def test_fim_extract_and_build():
    code = ("def add(a, b):\n    total = a + b\n    return total\n\n"
            "def mul(a, b):\n    return a * b\n")
    funcs = extract_functions(code)
    assert len(funcs) == 2
    rng = random.Random(0)
    fim = make_fim(funcs[0] * 2, rng)   # ensure long enough
    assert fim is not None
    assert FIM_PREFIX in fim and FIM_MIDDLE in fim


# ---------------- RDS format: roundtrip, random access, checksum ----------------
def _run_pipeline(tmp, **cfg_kw):
    root, out = os.path.join(tmp, "in"), os.path.join(tmp, "out")
    build_sample(root)
    cfg = RDEConfig(seq_len=64, vocab_size=259, tokenizer_version=0, **cfg_kw)
    tok = ByteTokenizer()
    manifest = RDEPipeline(tok, cfg).run(root, out, verbose=False, now_iso=NOW)
    return root, out, cfg, tok, manifest


def test_pipeline_end_to_end_and_random_access():
    tmp = tempfile.mkdtemp()
    try:
        _, out, _, _, manifest = _run_pipeline(tmp)
        ds = RDSDataset(out)
        assert len(ds) > 0
        assert ds.verify() is True
        # random access mid-dataset == direct shard read
        idx = len(ds) // 2
        chunk = ds[idx]
        assert len(chunk) == manifest["seq_len"]
        m = ds.meta(idx)
        assert "repo" in m and "difficulty" in m
        ds.close()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_deterministic_shuffle_and_worker_split():
    tmp = tempfile.mkdtemp()
    try:
        _, out, _, _, _ = _run_pipeline(tmp)
        ds = RDSDataset(out)
        assert ds.indices(seed=7) == ds.indices(seed=7)            # deterministic
        w0 = set(ds.indices(seed=1, worker_id=0, num_workers=3))
        w1 = set(ds.indices(seed=1, worker_id=1, num_workers=3))
        w2 = set(ds.indices(seed=1, worker_id=2, num_workers=3))
        assert w0.isdisjoint(w1) and w1.isdisjoint(w2)
        assert (w0 | w1 | w2) == set(range(len(ds)))               # complete cover
        ds.close()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_multi_shard_rotation():
    tmp = tempfile.mkdtemp()
    try:
        _, out, _, _, manifest = _run_pipeline(tmp, shard_max_bytes=640)
        assert manifest["n_shards"] >= 2
        assert all(sh["checksum_ok"] for sh in manifest["shards"])
        ds = RDSDataset(out)
        assert len(ds[len(ds) - 1]) == 64      # last chunk in a later shard readable
        ds.close()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_checksum_detects_corruption():
    tmp = tempfile.mkdtemp()
    try:
        _, out, _, _, _ = _run_pipeline(tmp)
        shard = os.path.join(out, "shard_00000.rds")
        with open(shard, "r+b") as f:
            f.seek(80)                          # flip a byte inside DATA
            b = f.read(1)
            f.seek(80)
            f.write(bytes([b[0] ^ 0xFF]))
        with RDSReader(shard) as r:
            assert r.verify_checksum() is False
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# ---------------- manifest lock + versioning ----------------
def test_manifest_lock_and_replay():
    tmp = tempfile.mkdtemp()
    try:
        _, _, cfg, tok, manifest = _run_pipeline(tmp, dataset_version="2.0.0")
        lock = manifest["lock"]
        assert lock["dataset_version"] == "2.0.0"
        assert lock["creation_time"] == NOW
        assert lock["tokenizer_hash"] == tokenizer_hash(tok)
        assert verify_lock(lock, cfg, tok) == []          # same config replays clean
        cfg2 = RDEConfig(seq_len=128, vocab_size=259)     # changed
        assert verify_lock(lock, cfg2, tok)               # mismatch detected
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_version_registry():
    assert 1 in SUPPORTED_VERSIONS


# ---------------- packing stats + report ----------------
def test_packing_stats_and_report_files():
    tmp = tempfile.mkdtemp()
    try:
        _, out, _, _, manifest = _run_pipeline(tmp)
        pk = manifest["stats"]["packing"]
        assert 0 <= pk["packing_efficiency_pct"] <= 100
        assert pk["real_tokens"] + pk["pad_tokens"] == pk["capacity_tokens"]
        assert os.path.exists(os.path.join(out, "report.json"))
        assert os.path.exists(os.path.join(out, "report.html"))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# ---------------- input layouts + empty-dataset guard ----------------
def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


def _build(root, out):
    tok = ByteTokenizer()
    cfg = RDEConfig(seq_len=64, vocab_size=tok.vocab_size, tokenizer_version=0)
    return RDEPipeline(tok, cfg).run(root, out, verbose=False, now_iso=NOW)


def test_flat_layout_single_file():
    """root/<file>.py (no repo subdir) must be discovered — the reported bug."""
    tmp = tempfile.mkdtemp()
    try:
        _write(os.path.join(tmp, "in", "sample.py"),
               "def greet(name):\n    return 'hi ' + name\n")
        m = _build(os.path.join(tmp, "in"), os.path.join(tmp, "out"))
        assert m["stats"]["files_kept"] == 1
        assert m["stats"]["total_files_seen"] == 1
        assert m["n_shards"] == 1
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_multi_repo_layout():
    """root/<repo>/<files> still works (no regression)."""
    tmp = tempfile.mkdtemp()
    try:
        _write(os.path.join(tmp, "in", "repoA", "a.py"), "def a():\n    return 1\n")
        _write(os.path.join(tmp, "in", "repoB", "b.py"), "def b():\n    return 2\n")
        m = _build(os.path.join(tmp, "in"), os.path.join(tmp, "out"))
        assert m["stats"]["files_kept"] == 2
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_mixed_layout_no_double_processing():
    """Loose file + subdir: each file discovered exactly once."""
    tmp = tempfile.mkdtemp()
    try:
        _write(os.path.join(tmp, "in", "top.py"), "def top():\n    return 1\n")
        _write(os.path.join(tmp, "in", "sub", "deep.py"), "def deep():\n    return 2\n")
        m = _build(os.path.join(tmp, "in"), os.path.join(tmp, "out"))
        assert m["stats"]["total_files_seen"] == 2      # deep.py NOT seen twice
        assert m["stats"]["files_kept"] == 2
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_empty_dir_raises():
    """Zero files discovered -> descriptive error, no empty dataset written."""
    tmp = tempfile.mkdtemp()
    try:
        os.makedirs(os.path.join(tmp, "in"))
        try:
            _build(os.path.join(tmp, "in"), os.path.join(tmp, "out"))
            assert False, "expected EmptyDatasetError"
        except EmptyDatasetError as e:
            assert "empty dataset" in str(e).lower()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_all_filtered_raises():
    """Files exist but all filtered -> descriptive error mentioning drops."""
    tmp = tempfile.mkdtemp()
    try:
        with open(os.path.join(tmp, "bin.bin"), "wb") as f:
            f.write(b"\x00\x01\x02BINARY")
        os.makedirs(os.path.join(tmp, "in"), exist_ok=True)
        with open(os.path.join(tmp, "in", "bin.bin"), "wb") as f:
            f.write(b"\x00\x01\x02BINARY")
        try:
            _build(os.path.join(tmp, "in"), os.path.join(tmp, "out"))
            assert False, "expected EmptyDatasetError"
        except EmptyDatasetError as e:
            assert "filtered out" in str(e).lower()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_not_a_directory_raises():
    tmp = tempfile.mkdtemp()
    try:
        path = os.path.join(tmp, "a.py")
        with open(path, "w") as f:
            f.write("x = 1\n")
        try:
            _build(path, os.path.join(tmp, "out"))
            assert False, "expected EmptyDatasetError"
        except EmptyDatasetError as e:
            assert "not a directory" in str(e).lower()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    passed = 0
    for fn in fns:
        fn()
        print(f"  PASS  {fn.__name__}")
        passed += 1
    print(f"\n{passed}/{len(fns)} RDE tests passed ✅")
